### ISSUE TITLE
Add a delete option in the "images" menu

### ISSUE THREAD

**Issue by Audioslaver** [rsusik/simple-web-based-interface-for-scanner#1]
Would it be possible to delete the scanned images directly into the interface ?

**Comment by rsusik** [comment]
Not yet, but it's on TODO list. Recently, I found that printing functionality (also from URL) would be useful. I will probably add those features near July (I'm snowed under with work recently).

**Comment by rsusik** [comment]
Added :)

**Comment by Audioslaver** [comment]
Thank you !

Thomas Bourguignon
________________________________
