### ISSUE TITLE
Not scanning after update

### ISSUE THREAD

**Issue by Audioslaver** [rsusik/simple-web-based-interface-for-scanner#2]
Hi,
Ive updated Swis...and my scanner doesnt seem to scan anymore !
the scanner doesnt seem to process any request.

Uninstalling and reinstalling doesnt help :(

**Comment by rsusik** [comment]
Hi, 

Can you provide what below command returns?

`sudo swis service status`

Does downgrading solve the issue?

`pip install swis==0.3.13`

I guess not. It doesn't look like anything from the last change could make it happen. 

Maybe try running the configuration command:

```
sudo swis --ip [HOST IP ADDRESS] --port 5520 -u [USER] -g [GROUP] service install 
sudo swis service start
```

**Comment by Audioslaver** [comment]
Hi, here the log on the command :

Loaded: loaded (/etc/systemd/system/swis.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-08-11 13:01:47 CEST; 8h ago
   Main PID: 10290 (swis)
      Tasks: 2 (limit: 9304)
     Memory: 21.5M
        CPU: 58.086s
     CGroup: /system.slice/swis.service
             └─10290 /usr/bin/python3 /usr/local/bin/swis --nocfg -i 192.168.1.30 -p 5520 -d scans -u root -g root

août 11 13:01:47 ThinkCentre-M73 swis[10290]: INFO:     2023-08-11 13:01:47 [server.py:76] Started server process [10290]
août 11 13:01:47 ThinkCentre-M73 swis[10290]: INFO:     2023-08-11 13:01:47 [on.py:48] Waiting for application startup.
août 11 13:01:47 ThinkCentre-M73 swis[10290]: INFO:     2023-08-11 13:01:47 [on.py:62] Application startup complete.
août 11 13:01:47 ThinkCentre-M73 swis[10290]: INFO:     2023-08-11 13:01:47 [server.py:219] Uvicorn running on http://0.0.0.0:5520 (Press CTRL+C to quit)
août 11 13:02:03 ThinkCentre-M73 swis[10290]: INFO:     2023-08-11 13:02:03 (192.168.1.18:54640) [uvicorn.access] 192.168.1.18:54640 - "GET / HTTP/1.1" 307
août 11 13:02:03 ThinkCentre-M73 swis[10290]: INFO:     2023-08-11 13:02:03 (192.168.1.18:54640) [uvicorn.access] 192.168.1.18:54640 - "GET /app HTTP/1.1" 307
août 11 13:29:39 ThinkCentre-M73 swis[10290]: INFO:     2023-08-11 13:29:39 (192.168.1.18:52447) [uvicorn.access] 192.168.1.18:52447 - "GET / HTTP/1.1" 307
août 11 13:29:39 ThinkCentre-M73 swis[10290]: INFO:     2023-08-11 13:29:39 (192.168.1.18:52447) [uvicorn.access] 192.168.1.18:52447 - "GET /app HTTP/1.1" 307
août 11 13:30:04 ThinkCentre-M73 swis[10290]: INFO:     2023-08-11 13:30:04 (192.168.1.18:52462) [uvicorn.access] 192.168.1.18:52462 - "GET / HTTP/1.1" 307
août 11 13:30:04 ThinkCentre-M73 swis[10290]: INFO:     2023-08-11 13:30:04 (192.168.1.18:52462) [uvicorn.access] 192.168.1.18:52462 - "GET /app HTTP/1.1" 307

As configuration, I put root as users...but it doesnt look like it working :(

**Comment by rsusik** [comment]
Please execute the following:
`sudo swis service stop`

Then:
`sudo swis -i $(hostname -I)  -u "$USER" -g "$USER"`
(you can albo add `-d` for the destination folder, but please provide the full path)

Then execute scanning and paste the logs you see.

**Comment by Audioslaver** [comment]
I just did : sudo swis 192.168.1.30  -u "$USER".... and now its launched and works.
the service is still flagged as "failed to launch"
